In [1]:
import torch
import torchvision
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from torch.nn import *
from torch.optim import *
from torchvision.models import *
from sklearn.model_selection import *
from sklearn.metrics import *
import wandb
import nltk
from nltk.stem.porter import *
PROJECT_NAME = "Natural-Language-Processing-with-Disaster-Tweets"
np.random.seed(55)
stemmer = PorterStemmer()

In [2]:
def tokenize(sentence):
    return nltk.word_tokenize(sentence.lower())

In [3]:
tokenize("Testing this tokenize function")

['testing', 'this', 'tokenize', 'function']

In [4]:
def stem(word):
    return stemmer.stem(word.lower())

In [5]:
stem('organic')

'organ'

In [30]:
def words_to_int(words,all_words):
    new_words = []
    for word in words:
        new_words.append(stem(word))
    list_of_os = np.zeros(len(all_words))
    for i in range(len(all_words)):
        if all_words[i] in new_words:
            list_of_os[i] = 1.0
    return list_of_os

In [31]:
words_to_int("I am testing this",["testing","I","test","grswgre"])

array([0., 0., 1., 0.])

In [32]:
data = pd.read_csv('./data/train.csv')

In [34]:
X = data['text']
y = data['target']

In [36]:
all_words = []
tags = []

In [38]:
from tqdm import tqdm

In [41]:
for x_iter,y_iter in tqdm(zip(X,y)):
    x_iter = tokenize(x_iter)
    new_x_iter = []
    for x_iter_i in x_iter:
        new_x_iter.append(stem(x_iter_i))
    all_words.extend(new_x_iter)
    tags.append(y_iter)

7613it [00:02, 3537.61it/s]


In [44]:
np.random.shuffle(all_words)

In [45]:
all_words = sorted(set(all_words))

In [48]:
tags = sorted(set(tags))

In [49]:
new_X = []
new_y = []

In [50]:
for X_iter,y_iter in tqdm(zip(X,y)):
    new_X.append(words_to_int(X_iter,all_words))
    new_y.append(np.eye(tags.index(y_iter),len(tags)))

7613it [00:28, 268.74it/s]


In [51]:
new_X[0]

array([0., 1., 0., ..., 0., 0., 0.])

In [52]:
new_y[0]

array([[1., 0.]])